placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = true
thinnerBoundingBox = true
snowMakingIce = true
snowOnIce = true
snowNeverMelt = false
snowReduceFallDamage = true
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
#If you want to uninstall this mod, you probably want to make snow-covered blocks back to normal.
retainOriginalBlocks = false
snowMeltsInWarmBiomes = false

